version: '3.7'
services:
  db:
    image: postgres:14-alpine3.19
    ports:
      - 5433:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=infsus
volumes:
  data:
