spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
      name: infsus
  docker:
      compose:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/infsus
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

